feat: Implemented a ScopeManager with a default scope
NethermindEth/cairo-vm-go pull request #349
Opened 2024-04-10 22:03 UTC by fishonamos

I Initialized DefaultContext function in the hinter package. The modification initializes the ScopeManager with a default scope when creating a new HintRunnerContext. 

This ensures that the ScopeManager is always initialized with a default scope when necessary. This will resolve #345

2024-04-24 15:54 UTC, TAdev0 requested changes
@fishonamos hi, I think you just need to call `InitializeScopeManager` on `ctx` which is defined in scope.go file . You dont need to create a new `InitializeScopeManager` function.

Moreover, the first line of your function :
```
ctx.ScopeManager = *DefaultNewScopeManager()
```
already does the job of entering a new scope.  Indeed,  `DefaultNewScopeManager` function will execute `NewScopeManager(make(map[string]any)`, thus creating an  uninitialized scope which will be the main scope. The 2nd line will create another scope and it is not necessary.

Simply calling `ctx.InitializeScopeManager(make(map[string]any))` should work.

@cicr99  @rodrigo-pino  @MaksymMalicki  please correct me if I am wrong.

2024-04-24 16:13 UTC, fishonamos commented
> @fishonamos hi, I think you just need to call `InitializeScopeManager` on `ctx` which is defined in scope.go file . You dont need to create a new `InitializeScopeManager` function.
> 
> Moreover, the first line of your function :
> 
> ```
> ctx.ScopeManager = *DefaultNewScopeManager()
> ```
> 
> already does the job of entering a new scope. Indeed, `DefaultNewScopeManager` function will execute `NewScopeManager(make(map[string]any)`, thus creating an uninitialized scope which will be the main scope. The 2nd line will create another scope and it is not necessary.
> 
> Simply calling `ctx.InitializeScopeManager(make(map[string]any))` should work.
> 
> @cicr99 @rodrigo-pino @MaksymMalicki please correct me if I am wrong.

That makes sense. Done it

2024-04-24 16:24 UTC, TAdev0 commented on pkg/hintrunner/hinter/hinter.go
>  func InitializeDefaultContext() *HintRunnerContext {
If i'm right with what i said before, no need to add a new function `InitializeScopeManager` here. 

Simply doing : 
```
func InitializeDefaultContext() *HintRunnerContext {
	ctx := &HintRunnerContext{
		DictionaryManager:         DictionaryManager{},
		SquashedDictionaryManager: SquashedDictionaryManager{},
		ConstantSizeSegment:       mem.UnknownAddress,
	}
	InitializeScopeManager(ctx, make(map[string]any)) // Initialize the ScopeManager with a default scope
	return ctx
}
```

should work

2024-04-24 17:08 UTC, TAdev0 commented on pkg/hintrunner/hinter/hinter.go
> +	InitializeScopeManager(ctx, make(map[string]any)) // Initialize the ScopeManager with a default scope
well, now i look at it again, it seems that the current main branch returns `&HintRunnerContext` with `ScopeManager: *DefaultNewScopeManager(),` . This is actually the same as doing  `InitializeScopeManager(ctx, make(map[string]any))` after removing the ScopeManager field. 

@cicr99  what do you think? I'm not sure this is what was asked with issue #345  . This file is the hinter.go and the hinter effectively creates a new context with a main scope uninitialized.

2024-04-24 17:25 UTC, TAdev0 commented on pkg/hintrunner/hinter/hinter.go
> +	InitializeScopeManager(ctx, make(map[string]any)) // Initialize the ScopeManager with a default scope
I guess the code that should be modified is in the `runHinterTests` function in zerohint_test.go  file? 

here : 

```
		ctx := &hinter.HintRunnerContext{}
		if tc.ctxInit != nil {
			tc.ctxInit(ctx)
		}
```
when running each test, the context is reset, with all its fields unitialized

2024-04-25 15:44 UTC, cicr99 commented
Hey @fishonamos 
For this issue what you need to modify is https://github.com/NethermindEth/cairo-vm-go/blob/b2602abd7a2901daba66ead1bc2805d200538ee2/pkg/hintrunner/zero/zerohint_test.go#L119 as @TAdev0 mentioned in his last comment
The idea is to initialize the scope manager for all tests and not having to do it manually.
In addition, you'll notice that there are some unit tests that have something like the following (see [here](https://github.com/NethermindEth/cairo-vm-go/blob/b2602abd7a2901daba66ead1bc2805d200538ee2/pkg/hintrunner/zero/zerohint_ec_test.go#L26C5-L28C7)):
```
ctxInit: func(ctx *hinter.HintRunnerContext) {
	ctx.ScopeManager.EnterScope(map[string]any{})
},
```
or (see [here](https://github.com/NethermindEth/cairo-vm-go/blob/b2602abd7a2901daba66ead1bc2805d200538ee2/pkg/hintrunner/zero/zerohint_signature_test.go#L123C5-L125C7)):
```
ctxInit: func(ctx *hinter.HintRunnerContext) {
	hinter.InitializeScopeManager(ctx, map[string]any{})
},
```
The idea for these, as you can see is just to initialize the ScopeManager, so once you modify the code to initialize it all the time, that won't be necessary, then those lines can be removed. Make sure to check all test cases for situations like these.

2024-05-02 10:39 UTC, closed without merging

2024-05-02 10:47 UTC, TAdev0 commented
@fishonamos did you close the PR by mistake?

2024-05-02 11:22 UTC, fishonamos commented
Just seeing this. I think it is a mistake.  But not an issue. I will raise
another today. I have found a way.

On Thu, 2 May 2024, 11:48 am Tristan, ***@***.***> wrote:

> @fishonamos <https://github.com/fishonamos> did you close the PR by
> mistake?
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/NethermindEth/cairo-vm-go/pull/349#issuecomment-2090179649>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AKOUVHO6N7LZUOWAJUFR77DZAIKWFAVCNFSM6AAAAABGBGV5QKVHI2DSMVQWIX3LMV43OSLTON2WKQ3PNVWWK3TUHMZDAOJQGE3TSNRUHE>
> .
> You are receiving this because you were mentioned.Message ID:
> ***@***.***>
>