Issue/233 usort verify
NethermindEth/cairo-vm-go pull request #358
Opened 2024-04-17 14:49 UTC by pxyxyrus

Issue https://github.com/NethermindEth/cairo-vm-go/issues/233

Implement UsortVerify hint

Added test for UsortVerify hint

2024-04-18 11:12 UTC, MaksymMalicki requested changes

2024-04-18 11:12 UTC, MaksymMalicki commented on pkg/hintrunner/zero/zerohint_usort.go
> +			positionsDict, ok := positionsDictInterface.(map[uint64][]*fp.Element)
I belive if you check [this](https://github.com/starkware-libs/cairo-lang/blob/efa9648f57568aad8f8a13fbf027d2de7c63c2c0/src/starkware/cairo/common/usort.cairo#L8) function, you will see, that verify usort is being called at the end and is being executed in the same scope as this [PR](https://github.com/NethermindEth/cairo-vm-go/pull/352/files) (implements usort method). Notice that positionsDict is of type map[fp.Element][]uint64. Make sure that all the types are compatible with this PR. 
I noticed, that in my [PR](https://github.com/NethermindEth/cairo-vm-go/pull/352/files) I need to pass positionsDict into the scope for you to read it in this hint, but I don't know if we can pass maps into scopes or is it the functionality of a DictManager. @rodrigo-pino do you have any thoughts?

2024-04-18 11:12 UTC, MaksymMalicki commented on pkg/hintrunner/zero/zerohint_usort.go
> +			value, err := hinter.ResolveAsUint64(vm, value)
same here, to make those hints compatible, the value must be a Felt

2024-04-18 11:12 UTC, MaksymMalicki commented on pkg/hintrunner/zero/zerohint_usort_test.go
> +							0: {feltUint64(1), feltUint64(2), feltUint64(3)},
change type of positions_dict

2024-04-18 11:12 UTC, MaksymMalicki commented on pkg/hintrunner/zero/zerohint_usort_test.go
> +					lastPos, err := ctx.runnerContext.ScopeManager.GetVariableValue("last_pos")
I think we have an utility for hits called varValueInScopeEquals()

2024-04-26 05:38 UTC, cicr99 commented on pkg/hintrunner/zero/zerohint_usort.go
> +
This is not the correct code for this hint. The one corresponding to this hint should be this [one](https://github.com/starkware-libs/cairo-lang/blob/efa9648f57568aad8f8a13fbf027d2de7c63c2c0/src/starkware/cairo/common/usort.cairo#L15)

2024-04-26 05:38 UTC, cicr99 commented on pkg/hintrunner/zero/zerohint_usort.go
> +
I just noticed you didn't add the code in the constructor of the `UsortVerify` hint, so it was probably that you wrote it in this method by mistake. Could you please add the corresponding codes in both functions?

2024-04-26 05:38 UTC, cicr99 commented on pkg/hintrunner/zero/zerohint_usort.go
> +			return nil
You can just return `err` at the end, so even better, just directly return the result of `AssignVariables` method
```
return ctx.ScopeManager.AssignVariables(map[string]any{
	"last_pos":  0,
	"positions": positions,
})
```

2024-05-01 08:24 UTC, cicr99 approved these changes

2024-05-01 10:33 UTC, MaksymMalicki approved these changes

2024-05-01 12:33 UTC, merged