[feat] added a default scope manager
NethermindEth/cairo-vm-go pull request #382
Opened 2024-05-02 16:08 UTC by fishonamos

Modified the code so when the context is created, the Scope Manager is also initialised. This will solve #345

2024-05-02 16:29 UTC, TAdev0 commented
@fishonamos  hi, your code will not compile because `NewScopeManager` takes a `map[string]any` as argument. 
What you can do instead is calling `*hinter.DefaultNewScopeManager()` , and `DefaultNewScopeManager` will call `NewScopeManager` for you passing an empty array as argument.

2024-05-02 16:49 UTC, TAdev0 commented
Basically, you have 2 possibilities: 

- manually defining the ScopeManager field of `ctx` 
```
	ctx := &hinter.HintRunnerContext{
			ScopeManager: *hinter.DefaultNewScopeManager(),
		}
```
- creating an uninitialized `ctx` an calling `InitializeScopeManager` on it , passing an empty array of string
```
		ctx := &hinter.HintRunnerContext{}
		hinter.InitializeScopeManager(ctx, make(map[string]any))

```

2024-05-02 17:12 UTC, fishonamos commented
> Basically, you have 2 possibilities:
> 
> * manually defining the ScopeManager field of `ctx`
> 
> ```
> 	ctx := &hinter.HintRunnerContext{
> 			ScopeManager: *hinter.DefaultNewScopeManager(),
> 		}
> ```
> 
> * creating an uninitialized `ctx` an calling `InitializeScopeManager` , passing `ctx`  and an empty array of string to initialize the ScopeManager field:
> 
> ```
> 		ctx := &hinter.HintRunnerContext{}
> 		hinter.InitializeScopeManager(ctx, make(map[string]any))
> ```

Thank you. Learnt a lot here. I used the Uninitialized ctx option. This creates an empty HintRunnerContext first, then  initializes the ScopeManager using InitializeScopeManager().

2024-05-02 17:22 UTC, TAdev0 requested changes

2024-05-02 17:22 UTC, TAdev0 commented on pkg/hintrunner/zero/zerohint_test.go
> -		if tc.ctxInit != nil {
Why did you remove these lines?

2024-05-02 18:33 UTC, fishonamos commented on pkg/hintrunner/zero/zerohint_test.go
> -		if tc.ctxInit != nil {
Oh. A deletion error.

2024-05-02 19:33 UTC, TAdev0 commented
LGTM!

@cicr99  should we merge this like this and open another PR to modify every test to be consistent with the default initialized scope manager?

2024-05-03 09:56 UTC, TAdev0 commented
there is a unit test failing after merging the main branch.

This is becasue of `UsortVerify` test that uses `InitializeScopeManager` to create a scope with `positions_dict` . But as we already call `InitializeScopeManager` in the general test setting, it wont work.

Can you modify the `UsortVerify` so that it calls `ctx.ScopeManager.EnterScope` instead?

2024-05-03 10:21 UTC, TAdev0 commented
yes `AssignVariable` is enough, you are right. I'll do a PR to update all tests configuration once this one is merged anyway

2024-05-03 16:54 UTC, fishonamos commented
I modified  "Usort Verify" to call just Assign Variable. I think we need to do for all others too.  Such as UsortVerifyMultiplicityAssert.

2024-05-03 16:56 UTC, TAdev0 commented
hi @fishonamos , yes i will update all other tests in another PR to make sure we never create unnecessary scopes :)

2024-05-03 16:57 UTC, TAdev0 commented
@fishonamos  your unit test dont pass. You should use `make build` and `make unit` to run tests locally and make sure they pass

2024-05-03 16:58 UTC, TAdev0 commented
you need to check the return value with `AssignVariable`

2024-05-03 17:01 UTC, fishonamos commented
They are now passing
![Uploading Screenshot 2024-05-04 at 02.03.04.png…]()

2024-05-03 17:05 UTC, TAdev0 commented
you need to check the return value with AssigneVariable

```

err = ctx.ScopeManager.AssignVariable("...", ...)
 if err != nil {
       return err
 }
```

2024-05-03 17:19 UTC, fishonamos commented
All tests have passed.

2024-05-03 17:27 UTC, TAdev0 commented
lgtm!

2024-05-03 17:27 UTC, TAdev0 approved these changes

2024-05-03 17:27 UTC, merged

2024-05-03 17:49 UTC, TAdev0 commented
well we should probably have used 
```
		if err != nil {
						t.Fatal(err)
					}
```

in unit tests, but anyway it doesnt matter, and i'm pushing soon a pr that will update this