Keccak hints integration tests
NethermindEth/cairo-vm-go pull request #462
Opened 2024-06-13 18:00 UTC by MaksymMalicki

2024-06-14 09:59 UTC, cicr99 commented on pkg/hintrunner/zero/zerohint.go
> +		fmt.Println(rawHint.Code)
I think you can remove this line. But it could be a good idea to add the code of the unidentified hint in the error message. Could you pls do that?

2024-06-14 09:59 UTC, cicr99 commented on pkg/hintrunner/zero/zerohint_keccak.go
> +func newCompareKeccakFullRateInBytesNondetCode(nBytes hinter.ResOperander) hinter.Hinter {
The format of the function name, should have `Hint` suffix instead of `Code`

2024-06-14 09:59 UTC, cicr99 commented on pkg/hintrunner/zero/zerohint_keccak.go
> +func createCompareKeccakFullRateInBytesNondetCode(resolver hintReferenceResolver) (hinter.Hinter, error) {
Same here, but with `Hinter` suffix

2024-06-14 09:59 UTC, cicr99 commented on pkg/hintrunner/zero/zerohint_keccak_test.go
> +		"CompareKeccakFullRateInBytesNondetCode": {
Also, suffix here

2024-06-25 16:13 UTC, TAdev0 commented on pkg/hintrunner/zero/zerohint_keccak.go
> +			//> memory[ap] = to_felt_or_relocatable(ids.n_bytes < ids.BYTES_IN_WORD)
I know that in whitelisted json file, this is the hint written, but if you check the flow in keccak stuff, the hint is : 

```
ids.n_bytes < ids.BYTES_IN_WORD
```
see : 

https://github.com/starkware-libs/cairo-lang/blob/efa9648f57568aad8f8a13fbf027d2de7c63c2c0/src/starkware/cairo/common/cairo_keccak/keccak.cairo#L211

2024-06-25 16:14 UTC, TAdev0 requested changes

2024-06-25 16:14 UTC, TAdev0 commented on pkg/hintrunner/zero/zerohint_keccak.go
> +			//> memory[ap] = to_felt_or_relocatable(ids.n_bytes >= ids.KECCAK_FULL_RATE_IN_BYTES)
same here

2024-06-25 16:27 UTC, TAdev0 commented
@MaksymMalicki  i think the `nondet` in Cairo zero means in the json  is added `memory[ap] = to_felt_or_relocatable( ` 
explaining why the hint in the whitelist is not exactly the same as in the code of keccak functions

2024-07-04 10:07 UTC, cicr99 commented
Closing this draft as #497 already contains most of this changes, and there are too many conflicts in this one

2024-07-04 10:07 UTC, closed without merging